dist: trusty

language: node_js

node_js:
    - "8"
    - "10"
    - "11"
    - "12"
    - "13"

before_script:
    - cd dependency
    - npm install
    - npm pack
    - cd ..
    - cd dependent
    - npm install

script:
    - npm test
